<Project>
  <PropertyGroup>
    <VersionPrefix>0.1.0</VersionPrefix>
    <VersionSuffix>alpha</VersionSuffix>
    <AssemblyVersion>0.1.0.0</AssemblyVersion>
    <FileVersion>0.1.0.0</FileVersion>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
</Project>
